## Analysis of health status for US population

* Dependences

In [6]:
import os
import csv
%matplotlib inline

import matplotlib.pyplot as plt


import collections
import pandas as pd
import numpy as np
import requests
import time
import datetime

* Loaded file 
* Readed  file and stored into Pandas data frame

In [7]:
file_to_load = "Sacramento_Crime_Data_From_Current_Year.csv"

Sac_crime_df = pd.read_csv(file_to_load, delimiter=',', encoding="utf-8", dtype={'Time Occurred':str})
Sac_crime_df.head()

,OBJECTID,Record_ID,Offense_Code,Offense_Ext,Offense_Category,Description,Police_District,Beat,Grid,Occurence_Date
0,1001,1432285,5400,1,TRAFFIC,TRAFFIC ACCIDENT-NON-INJURY,4,4A,0905,2020-01-10T00:20:05.000Z
1,1002,1432286,2399,2,LARCENY,484 PC PETTY THEFT,6,6C,1111,2020-01-12T00:22:00.000Z
2,1003,1432287,2202,0,BURGLARY,459 PC BURG RESIDENCE-FORCE,5,5A,1501,2020-01-10T00:09:30.000Z
3,1004,1432290,2399,2,LARCENY,484 PC PETTY THEFT,2,2C,0619,2020-01-09T00:16:45.000Z
4,1005,1432293,2299,01,BURGLARY,459 PC BURG VEHICLE,3,3M,0742,2020-01-13T00:21:00.000Z

In [8]:

# #Shrink data frame
# accident_df = collision_df.loc[:, ["Victim Descent", "Victim Age", 
#                                     "Date Occurred", "Time Occurred"]]
# # Reset index after shrunken dataframe and dropna applied
# accident_df.reset_index(drop=True, inplace=True)

# # # format age column
# accident_df['Victim Age'] = accident_df['Victim Age'].apply(np.int64)

# # format date column
Sac_crime_df['Occurence_Date'] = Sac_crime_df['Occurence_Date'].str[:10]
Sac_crime_df.loc[:,'Occurence_Date'] = Sac_crime_df['Occurence_Date'].astype("datetime64[ns]")
Sac_crime_df['Day of Week'] = Sac_crime_df['Occurence_Date'].dt.weekday_name

# # format time column
# Sac_crime_df['Hour'] = Sac_crime_df['Occurence_Date'].str[:2]

Sac_crime_df.head()

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [5]:
Sac_crime_df['Occurence_Date'] = Sac_crime_df['Occurence_Date'].str[:10]
# Sac_crime_df.loc[:,"Occurence_Date"] = Sac_crime_df["Occurence_Date"].astype("datetime64[ns]")
# accident_df['Day of Week'] = accident_df['Date Occurred'].dt.weekday_name

# # format time column
Sac_crime_df['Hour'] = Sac_crime_df['Occurence_Date'].str[:2]

Sac_crime_df.head(20)

,OBJECTID,Record_ID,Offense_Code,Offense_Ext,Offense_Category,Description,Police_District,Beat,Grid,Occurence_Date,Hour
0,1001,1432285,5400,1,TRAFFIC,TRAFFIC ACCIDENT-NON-INJURY,4,4A,0905,2020-01-10,20
1,1002,1432286,2399,2,LARCENY,484 PC PETTY THEFT,6,6C,1111,2020-01-12,20
2,1003,1432287,2202,0,BURGLARY,459 PC BURG RESIDENCE-FORCE,5,5A,1501,2020-01-10,20
3,1004,1432290,2399,2,LARCENY,484 PC PETTY THEFT,2,2C,0619,2020-01-09,20
4,1005,1432293,2299,01,BURGLARY,459 PC BURG VEHICLE,3,3M,0742,2020-01-13,20
5,1006,1432294,2399,2,LARCENY,484 PC PETTY THEFT,5,5C,1623,2020-01-09,20
6,1007,1432296,1313,19,BATTERY,242 PC BATTERY CIVILIAN,3,3A,0776,2020-01-14,20
7,1008,1432297,1313,19,BATTERY,242 PC BATTERY CIVILIAN,6,6B,1003,2020-01-13,20
8,1009,1432299,5005,2,OBST JUDICIARY,166(A)(4) WILFUL DISOBEY CT OR,2,2A,0223,2020-01-12,20
9,1010,1432307,1299,0,ROBBERY,211 PC ROBBERY-UNSPECIFIED,5,5B,1618,2020-01-14,20
10,1011,1432309,2299,01,BURGLARY,459 PC BURG VEHICLE,1,1A,0336,2020-01-12,20
11,1012,1432310,2399,23,LARCENY,487(A) GRAND THFT-RECYCL METAL,4,4B,1344,2020-01-13,20
12,1013,1432311,2303,1,LARCENY,487(A) PC GRAND THEFT >$950,3,3A,0723,2020-01-14,20
13,1014,1432312,2303,1,LARCENY,487(A) PC GRAND THEFT >$950,6,6A,1015,2020-01-13,20
14,1015,1432313,2299,01,BURGLARY,459 PC BURG VEHICLE,6,6D,0834,2020-01-14,20
15,1016,1432314,2205,3,BURGLARY,459.5 BURGLARY SHOPLIFT < $950,3,3B,0737,2020-01-13,20
16,1017,1432315,2399,2,LARCENY,484 PC PETTY THEFT,1,1C,0437,2020-01-14,20
17,1018,1432316,2399,2,LARCENY,484 PC PETTY THEFT,2,2A,0234,2020-01-11,20
18,1019,1432317,2204,0,BURGLARY,459 PC BURG RESIDENCE-NO FORCE,6,6D,0804,2020-01-12,20
19,1020,1432318,5400,1,TRAFFIC,TRAFFIC ACCIDENT-NON-INJURY,1,1C,0419,2020-01-14,20

In [ ]:
month_list=[]
year_list=[]
for a in Sac_crime_df['Occurence_Date']:
    a.split('-')
    year,month,date=a.split('-')
    month_list.append(month)
    year_list.append(year)

In [ ]:
month_list

In [ ]:
month_list=[]
year_list=[]
for a in Sac_crime_df['Occurence_Date']:
    a.split('-')
    year,month,date=a.split('-')
    month_list.append(month)
    year_list.append(year)

January=[]
February=[]
March=[]
April=[]
May=[]
June=[]
July=[]
August=[]
September=[]
October=[]
November=[]
December=[]

for i in month_list:
    if (i=='01'):
        January.append(i)
    elif (i=='02'):
        February.append(i)   
    elif (i=='03'):
        March.append(i)
    elif (i=='04'):
        April.append(i)
    elif (i=='05'):
        May.append(i)
    elif (i=='06'):
        June.append(i)
    elif (i=='07'):
        July.append(i)
    elif (i=='08'):
        August.append(i)
    elif (i=='09'):
        September.append(i)
    elif (i=='10'):
        October.append(i)
    elif (i=='11'):
        November.append(i)
    elif (i=='12'):
        December.append(i)

In [ ]:
January

In [ ]:
#old

* Copied relevant columns.

In [ ]:

x = ["State", "Deaths", "Year"]
df_data_needed = healthStatus_df[x].copy()

* Filtered data for certain years
* Grouped data by state
* Calculated the number of deaths in 2010.
* Reset index for dataframe

In [ ]:
df_data_needed_2010=df_data_needed.loc[df_data_needed['Year'] ==2010]
df_data_grouped_2010=df_data_needed_2010.groupby(df_data_needed_2010['State'])
Number_mortality_df_2010=pd.DataFrame({"Deaths_in_2010":df_data_grouped_2010["Deaths"].sum()})
Number_mortality_df_2010=Number_mortality_df_2010.reset_index()

* Removed unnecessary rows
* Reset, drop index

In [ ]:
Number_mortality_df_2010=Number_mortality_df_2010[( Number_mortality_df_2010.State!='United States')]

Number_mortality_df_2010= Number_mortality_df_2010.reset_index(drop=True)
Number_mortality_df_2010.head()

* Filtered data for certain years
* Grouped data by state
* Calculated the number of deaths in 2015.
* Reset index for dataframe

In [ ]:
df_data_needed_2015=df_data_needed.loc[df_data_needed['Year'] ==2015]
df_data_grouped_2015=df_data_needed_2015.groupby(df_data_needed_2015['State'])
Number_mortality_df_2015=pd.DataFrame({"Deaths_in_2015":df_data_grouped_2015["Deaths"].sum()})
Number_mortality_df_2015=Number_mortality_df_2015.reset_index()

* Removed unnecessary rows
* Reset, drop index

In [ ]:
Number_mortality_df_2015=Number_mortality_df_2015[( Number_mortality_df_2015.State!='United States')]
Number_mortality_df_2015= Number_mortality_df_2015.reset_index(drop=True)

Number_mortality_df_2015.head()

* Loaded file
* Readed file and stored into Pandas data frame

In [ ]:
file_to_load2 = "states.csv"

insurance_df = pd.read_csv(file_to_load2, delimiter=',', encoding="utf-8", dtype={'Time Occurred':str})

insurance_df.head()

* Copied relevant columns.

In [ ]:
y = ["State", "Uninsured Rate (2010)", "Uninsured Rate (2015)"]
needed_insurance_df= insurance_df[y].copy()
needed_insurance_df.head()

* Removed unnecessary rows

In [ ]:
needed_insurance_df=needed_insurance_df[(needed_insurance_df.State!='United States')]
needed_insurance_df.head()

In [ ]:
file_to_load3 = "Population.csv"

population_df = pd.read_csv(file_to_load3, delimiter=',', encoding="utf-8", dtype={'Time Occurred':str})
population_df.head()

In [ ]:
# population_df=population_df[(needed_insurance_df.State!='United States')]
# population_df=population_df.drop('Unnamed:1', axis=1)

* Cleaned whitespaces and made lowercase "State" column

In [ ]:
Number_mortality_df_2015["State"] = Number_mortality_df_2015["State"].apply(lambda x : x.lower().strip())
needed_insurance_df["State"] = needed_insurance_df["State"].apply(lambda x : x.lower().strip())
Number_mortality_df_2010["State"] = Number_mortality_df_2010["State"].apply(lambda x : x.lower().strip())
population_df["State"]=population_df["State"].apply(lambda x : x.lower().strip())

* Joined dataframes

In [ ]:
merged_df_one = pd.merge( Number_mortality_df_2015, needed_insurance_df, on="State", how='left')
merged_df_one.head()

In [ ]:
merged_df_two=pd.merge(population_df, merged_df_one, on="State", how='left')
merged_df_two.head()

* Joined dataframes
* Changed names of columns of final dataframe

In [ ]:
merged_df_final = pd.merge(Number_mortality_df_2010, merged_df_two, on="State", how='left')

merged_df_final = merged_df_final.rename(columns={"State": "State",
                                      "Deaths_in_2010": "Deaths_in_2010",
                                       "Population_Year_2010" :"Population_Year_2010",
                                      "Population_Year_2015":"Population_Year_2015",
                                      "Deaths_in_2015": "Deaths_in_2015",
                                      "Uninsured Rate (2010)": "Uninsured_Rate_2010",
                                      "Uninsured Rate (2015)": "Uninsured_Rate_2015"})
merged_df_final["Uninsured_Rate_2010"] = merged_df_final["Uninsured_Rate_2010"].astype('').dtypes
merged_df_final.head()

* Stored dataframe to a SQL database.

In [ ]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://test:test@localhost:5432/ETL_project", echo=False)

merged_df_final.to_sql("Number_mortality", con=engine,index=False, if_exists="replace")